yaml

name: Run Python script

on: [push]

jobs:
run-script:
runs-on: ubuntu - latest
name: Run clean_temp_files.py
steps:
- name: Checkout repository
uses: actions/checkout@v4

- name: Set up Python
uses: actions/setup-python@v5
with:
python-version: '3.13.5'

- name: Run clean_temp_files.py
run: python_clean_temp_files.py

